import math
TILESIZE = 32
EILES = 10
STULPAI = 15

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FOV = math.pi/3
RES = 1
NUM_RAYS = 160
HALF_WIDTH = WINDOW_WIDTH/2
SCALE = WINDOW_WIDTH // NUM_RAYS
HALF_HEIGHT = WINDOW_HEIGHT//2

DIST = WINDOW_WIDTH / (2 * math.tan(FOV/2))
PROJ_COEFF = DIST * TILESIZE

# raycast render
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS


# sprites
SCREEN_DIST = (WINDOW_WIDTH/2) / (math.tan(FOV/2))
